### ISSUE TITLE
在Truenas下运行，感觉测试结果是从内存跑出来的

### ISSUE THREAD

**Issue by sakuyamaij** [bihell/fio#1]
```
Executing Default test:
                    Read [MB/s]     Read [IOPS]    Write [MB/s]    Write [IOPS]
     SEQ1M-Q8T1            8073            8073            6179            6179
    RND4K-Q32T1            1285          329031             240           61614
     SEQ1M-Q1T1           11688           11688            8828            8828
     RND4K-Q1T1            1319          337685             624          159918
```

好的不正常

**Comment by bihell** [comment]
不应该，你是按照默认跑的么

**Comment by sakuyamaij** [comment]
是的，truenas下sudo bash fio_mark.sh /mnt/ssd
脚本文件直接wget下来的没有做任何改动

**Comment by bihell** [comment]
TrueNas-➜  ~ sudo bash fio_mark.sh /mnt/test
[sudo] password for admin:
Executing Default test:
                    Read [MB/s]     Read [IOPS]    Write [MB/s]    Write [IOPS]
     SEQ1M-Q8T1            1466            1465             735             735
    RND4K-Q32T1              19            5096               7            1796
     SEQ1M-Q1T1            1680            1680             502             502
     RND4K-Q1T1              23            6068              15            4017

我刚测了一遍很正常，你这个池有做什么特殊设置么？
